In [1]:
!gdown 1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a


Downloading...
From: https://drive.google.com/uc?id=1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a
To: /content/survey_large.txt
100% 21.8M/21.8M [00:00<00:00, 268MB/s]


In [2]:
import numpy as np

In [5]:
scores = np.loadtxt('survey_large.txt', dtype='int')
scores

array([ 7, 10,  5, ...,  9,  5,  9])

In [8]:
scores.size

10000000

In [9]:
scores.min()

1

In [11]:
scores.max()

10

In [12]:
scores.mean()

7.250214

In [14]:
#detractors

detractors = scores[scores<7]
detractors

array([5, 4, 4, ..., 5, 4, 5])

In [17]:
detractors.size

2844902

In [15]:
#promoters

promoters = scores[scores>8]
promoters

array([10,  9,  9, ..., 10,  9,  9])

In [16]:
promoters.size

5218510

In [21]:
nps = (promoters.size - detractors.size)/scores.size
nps = nps*100
print(nps)

23.73608
